name: CI

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-image .

      # - name: SonarCloud Scan
      #   uses: sonarsource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectBaseDir=./  # Adjust if your project is located in a subdirectory
      #       -Dsonar.java.source=11 /  # Adjust Java version if necessary
      #       -X

      - name: Trivy Scan
        run: |
          docker pull my-image
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy my-image

      - name: Send Report via Email
        run: |
          echo "Sending reports via email..."

      - name: Display Report in Console
        run: |
          echo "SonarCloud and Trivy reports:"
          cat sonarcloud_report.json  # Adjust this based on actual report file generated by SonarCloud
          cat trivy_report.txt        # Adjust this based on actual report file generated by Trivy
