name: CI

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t app:latest .
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}

      - name: Trivy Scan
        run: |
          docker pull app:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image app:latest

      - name: Send Report via Email
        run: echo "Sending reports via email..."

      - name: Display Report in Console
        run: |
          echo "SonarCloud and Trivy reports:"
