name: CI

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branchh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t amaan00101/apppy:tagname .

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}  
          SONAR_ORGANIZATION: ${{ secrets.ORGANIZATION }} 

      - name: Trivy Scan
        run: |
          docker pull amaan00101/apppy:tagname
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image amaan00101/apppy:tagname

      - name: Send Report via Email
        run: |
          echo "Sending reports via email..."

      - name: Display Report in Console
        run: |
          echo "SonarCloud and Trivy reports:"
           
