name: SonarCloud & Trivy Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t amaan00101/apppy:tagname .
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}

      - name: Trivy Scan
        run: |
          docker pull amaan00101/apppy:tagname
          docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image amaan00101/apppy:tagname > trivy-report.txt
          cat trivy-report.txt

      - name: Display Trivy Report Contents
        run: |
          echo "Trivy Scan Report Contents:"
          cat ${GITHUB_WORKSPACE}/trivy-report.txt
        # Capture the contents of trivy-report.txt as an output
        id: display-trivy-report
        env:
          REPORT_CONTENTS: ${{ steps.display-trivy-report.outputs.report-contents }}

      - name: Send email with Trivy report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }} 
          subject: Trivy Scan Report
          to: amaan.dev01@gmail.com
          body: |
            Here is the Trivy scan report for the latest Docker image:
            
            ${{ env.REPORT_CONTENTS }}

      - name: Display Report in Console
        run: echo "SonarCloud and Trivy Scan Completed"
